apiVersion: v1
kind: Service
metadata:
  name: nodeport-service
  labels:
    type: frontend
    client: IBM
spec:
  type: NodePort
  selector:
    type: frontend
    client: IBM
  ports:
  - port: 80

