apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-hostpath
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /home/ec2-user/volume-test
    type: DirectoryOrCreate
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-hostpath
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: Pod
metadata:
  name: pod-using-pvc
spec:
  containers:
    - name: pvc-container
      image: ubuntu:22.04
      command: ["sleep", "infinity"]
      volumeMounts:
        - name: pvc-vol
          mountPath: /ynd
  volumes:
    - name: pvc-vol
      persistentVolumeClaim:
        claimName: pvc-hostpath