apiVersion: v1
kind: Pod
metadata:
  name: secret-pod
  labels:
    type: secret-ynd
    client: ynd
spec:
  containers:
    - name: secret-cont
      image: ubuntu:22.04
      command: ["sleep", "infinity"]
      volumeMounts:
        - name: myvolume1
          mountPath: /yndurgarao
          readOnly: true
  volumes:
    - name: myvolume1
      secret:
        secretName: mysecret
