apiVersion: v1
kind: Secret
metadata:
  name: secret
type: Opaque
data:
  username: ZHVyZ2E=        # base64 for "durga"
  password: UGFzc3dvcmQxMjM= # base64 for "Password123"
[root@ip-10-20-10-33 ec2-user]#


