#### Dcoker File Instruction for COPY  #########

[root@ip-10-20-10-205 Docker]# cat Dockerfile 
FROM ubuntu:latest
LABEL Maintained By = "Durga rao"
LABEL Version = "1.0"
RUN apt-get update -y
WORKDIR /Renuka
COPY . /Renuka
CMD ["bash"]
----------------------------------------------------------
[root@ip-10-20-10-205 Docker]# docker run -dit --name cont1 myimage:0.1
a3c8452aa7666fd2ccb0be9db4985b41b6ca0516afe7b1a9aaa5742fca064376
[root@ip-10-20-10-205 Docker]# docker exec -it cont1 bash
root@a3c8452aa766:/Renuka# ls
1.txt  2.txt  3.txt  4.txt  5.txt  Dockerfile
========================================================================
[root@ip-10-20-10-205 Docker]# cat Dockerfile 
FROM ubuntu:latest
LABEL Maintained By = "Durga rao"
LABEL Version = "1.0"
RUN apt-get update -y
WORKDIR /Renuka
COPY . /ynd
CMD ["bash"]
----------------------------------------------------------------------
[root@ip-10-20-10-205 Docker]# docker build -t myimage:0.2 .
[root@ip-10-20-10-205 Docker]# docker run -dit --name cont2 myimage:0.2 
ae9c956da049d17cd3a1c0b608bbdcc36056d1a61a695627d2d51947ad147f92
[root@ip-10-20-10-205 Docker]# docker exec -it cont2 bash
root@ae9c956da049:/Renuka# ls
root@ae9c956da049:/Renuka# cd /ynd
root@ae9c956da049:/ynd# ls 
1.txt  2.txt  3.txt  4.txt  5.txt  Dockerfile
==================================================================================
[root@ip-10-20-10-205 Docker]# ls
Dockerfile  copy
[root@ip-10-20-10-205 Docker]# cd copy
[root@ip-10-20-10-205 copy]# ls
1.txt  2.txt  3.txt  4.txt  5.txt
[root@ip-10-20-10-205 copy]# pwd
/home/ec2-user/Docker/copy
[root@ip-10-20-10-205 copy]# cd ..
[root@ip-10-20-10-205 Docker]# cat Dockerfile 
FROM ubuntu:latest
LABEL Maintained By = "Durga rao"
LABEL Version = "1.0"
RUN apt-get update -y
WORKDIR /Renuka
COPY copy/ /Renuka/
CMD ["bash"]
----------------------------------------------------------
[root@ip-10-20-10-205 Docker]# docker build -t myimage:0.4 .
[root@ip-10-20-10-205 Docker]# docker run -dit --name cont3 myimage:0.4
a36b9deefdb6c8fbd8bc8a027cb4605544f76d52652a657d00a555441d162f1d
[root@ip-10-20-10-205 Docker]# docker exec -it cont3 bash
root@a36b9deefdb6:/Renuka# ls
1.txt  2.txt  3.txt  4.txt  5.txt